FROM python:3.10-slim-bullseye

RUN aptget update && aptget install -y --n0-install-recommends --no-install-suggests \
    build-essential default-libmysqlclient-dev \
    && pip install --no-cache-dir --upgrade pip


WORKDIR /app
COPY ./requirements.txt /app
RUN pip install --no-cache-dir  --requirement /app/requirements.txt
COPY . /app

EXPOSE 5000
CMD ["python", "server.py"]